### ISSUE TITLE
vctk_22k files

### ISSUE THREAD

**Issue by Ashbajawed** [dhchoi99/NANSY#6]
where to get these files
     train: VCTK-Corpus/vctk_22k_train.txt
      eval: VCTK-Corpus/vctk_22k_val.txt
      test: VCTK-Corpus/vctk_22k_test.txt

**Comment by dhchoi99** [comment]
I used manually splitted set which showed better result on other tasks. 
I'll add random splitted set files soon, but I recommend to make those by your own.
> To train NANSY on English, we used two datasets, i.e., 1. VCTK4 [47], 2. train-clean-360
subset of LibriTTS3 [54]. We trained the model using 90% of samples for each speaker.

**Comment by Ashbajawed** [comment]
jo just to confrm these text files contains name with absolute path of wav files? like in the following pattern

./NANSY/data/VCTK-Corpus/txt/p232/p232_365.txt
./NANSY/data/VCTK-Corpus/txt/p232/p232_100.txt
./NANSY/data/VCTK-Corpus/txt/p232/p232_351.txt
./NANSY/data/VCTK-Corpus/txt/p232/p232_162.txt
./NANSY/data/VCTK-Corpus/txt/p232/p232_140.txt
./NANSY/data/VCTK-Corpus/txt/p232/p232_355.txt

**Comment by dhchoi99** [comment]
Relative path to wav files, splitted with `\`


Examples:
```
dhchoi@e51633478c6b:/raid/vision/dhchoi/data/VCTK-Corpus$ cat vctk_22k_train.txt | head -10
VCTK-Corpus/wav22/p225/p225_001-22k.wav|please call stella|p225
VCTK-Corpus/wav22/p225/p225_002-22k.wav|ask her to bring these things with her from the store|p225
VCTK-Corpus/wav22/p225/p225_003-22k.wav|six spoons of fresh snow peas five thick slabs of blue cheese and maybe a snack for her brother bob|p225
VCTK-Corpus/wav22/p225/p225_005-22k.wav|she can scoop these things into three red bags and we will go meet her wednesday at the train station|p225
VCTK-Corpus/wav22/p225/p225_007-22k.wav|the rainbow is a division of white light into many beautiful colors|p225
VCTK-Corpus/wav22/p225/p225_008-22k.wav|these take the shape of a long round arch with its path high above and its two ends apparently beyond the horizon |p225
VCTK-Corpus/wav22/p225/p225_009-22k.wav|there is  according to legend a boiling pot of gold at one end|p225
VCTK-Corpus/wav22/p225/p225_010-22k.wav|people look but no one ever finds it|p225
VCTK-Corpus/wav22/p225/p225_011-22k.wav|when a man looks for something beyond his reach his friends say he is looking for the pot of gold at the end of the rainbow|p225
VCTK-Corpus/wav22/p225/p225_012-22k.wav|throughout the centuries people have explained the rainbow in various ways|p225
```

**Comment by dhchoi99** [comment]
Added some references to [README](https://github.com/dhchoi99/NANSY/blob/master/README.md), so please check :)

## Datasets

Datasets used when training are:

- VCTK:
  - CSTR VCTK Corpus: English Multi-speaker Corpus for CSTR Voice Cloning Toolkit (version 0.92)
  - https://datashare.ed.ac.uk/handle/10283/3443
    For `data/VCTK-Corpus/vctk_22k_train.txt`, `vctk_22k_val.txt` and `vctk_22k_test.txt`, use files at [mindslab-ai/cotatron](https://github.com/mindslab-ai/cotatron/tree/master/datasets/metadata).
- LibriTTS:
  - Large-scale corpus of English speech derived from the original materials of the LibriSpeech corpus
  - https://openslr.org/60/
  - train-clean-360 set
    For `data/LibriTTS/libritts_train_clean_360_audiopath_text_sid_train.txt` and `libritts_train_clean_360_audiopath_text_sid_val.txt`, use files at [mindslab-ai/univnet](https://github.com/mindslab-ai/univnet/tree/master/datasets/metadata).
- CSS10:
  - CSS10: A Collection of Single Speaker Speech Datasets for 10 Languages
  - https://github.com/Kyubyong/css10
